### ISSUE TITLE
Account Searching

### ISSUE THREAD

**Issue by Emmett922** [Emmett922/ledgerlifeline#1]
Works for the most part, however, when typing in "0.00" or "active" it shows all accounts with "0.00" in it even if it is "5000.00" and all accounts regardless of active status because both "active" and "inactive" have "active" in it. The way it currently works is treating everything like a string, which helps a lot for simplicity, but ends up with odd issues like this.

**Comment by AbhTal** [comment]
Works, when searching using balance, make sure to type out the exact balance for it to show the account, for example if you seach 50, nothing will show up but if you type out the full balance of 5000.00, the account shows up. Also fixed the active and inactive error
